CREATE DATABASE IF NOT EXISTS cursos_crud;

USE cursos_crud;

CREATE TABLE IF NOT EXISTS cursos_crud.carros (
  id bigint not null auto_increment,
  nome varchar(255),
  descricao varchar(255),
  url_foto varchar(255),
  url_video varchar(255),
  latitude varchar(255),
  longitude varchar(255),
  tipo varchar(255), primary key (id)
);

#Clássicos
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Tucker 1948','Descrição Tucker 1948','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Tucker.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/tucker.mp4','-23.564224','-46.653156','classicos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Chevrolet Corvette','Descrição Chevrolet Corvette','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Chevrolet_Corvette.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/corvette.mp4','-23.564224','-46.653156','classicos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Chevrolet Impala Coupe','Descrição Chevrolet Impala Coupe','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Chevrolet_Impala_Coupe.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/chevrolet_impala.mp4','-23.564224','-46.653156','classicos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Cadillac Deville Convertible','Descrição Cadillac Deville Convertible','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Cadillac_Deville_Convertible.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/cadillac_deville.mp4','-23.564224','-46.653156','classicos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Chevrolet Bel-Air','Descrição Chevrolet Bel-Air','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Chevrolet_BelAir.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/chevrolet_bel_air.mp4','-23.564224','-46.653156','classicos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Cadillac Eldorado','Descrição Cadillac Eldorado','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Cadillac_Eldorado.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/cadillac_eldorado.mp4','-23.564224','-46.653156','classicos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Ferrari 250 GTO','Descrição Ferrari 250 GTO','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Ferrari_250_GTO.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/ferrari_gto.mp4','-23.564224','-46.653156','classicos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Dodge Challenger','Descrição Dodge Challenger','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Dodge_Challenger.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/dodge_challenger.mp4','','','classicos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Camaro SS 1969','Descrição Camaro SS 1969','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Camaro_SS.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/camaro_ss.mp4','-23.564224','-46.653156','classicos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Ford Mustang 1976','Descrição Ford Mustang 1976','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/Ford_Mustang.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/classicos/ford_mustang.mp4','-23.564224','-46.653156','classicos');

#Esportivos
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Ferrari FF','Descrição Ferrari FF','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/Ferrari_FF.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/ferrari_ff.mp4','44.532218','10.864019','esportivos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('AUDI GT Spyder','Descrição AUDI GT Spyder','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/Audi_Spyder.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/audi_gt.mp4','-23.564224','-46.653156','esportivos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Porsche Panamera','Descrição Porsche Panamera','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/Porsche_Panamera.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/porsche_panamera.mp4','-23.564224','-46.653156','esportivos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Lamborghini Aventador','Descrição Lamborghini Aventador','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/Lamborghini_Aventador.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/lamborghini_aventador.mp4','-23.564224','-46.653156','esportivos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Chevrolet Corvette Z06','Descrição Chevrolet Corvette Z06','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/Chevrolet_Corvette_Z06.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/chevrolet_corvette.mp4','-23.564224','-46.653156','esportivos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('BMW M5','Descrição BMW M5','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/BMW.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/bmw-m5.mp4','-23.564224','-46.653156','esportivos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Renault Megane RS Trophy','Descrição Renault Megane RS Trophy','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/Renault_Megane_Trophy.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/renault_megane.mp4','-23.564224','-46.653156','esportivos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Maserati Grancabrio Sport','Descrição Maserati Grancabrio Sport','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/Maserati_Grancabrio_Sport.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/renault_megane.mp4','-23.564224','-46.653156','esportivos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('McLAREN MP4-12C','Descrição McLAREN MP4-12C','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/McLAREN.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/mcLaren.mp4','-23.564224','-46.653156','esportivos');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('MERCEDES-BENZ C63 AMG','Descrição MERCEDES-BENZ C63 AMG','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/MERCEDES_BENZ_AMG.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/esportivos/mercedes.mp4','-23.564224','-46.653156','esportivos');

#Luxo
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Bugatti Veyron','Descrição Bugatti Veyron','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Bugatti_Veyron.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/bugatti_veyron.mp4','-23.564224','-46.653156','luxo');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Ferrari Enzo','Descrição Ferrari Enzo','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Ferrari_Enzo.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/ferrari_enzo.mp4','-23.564224','-46.653156','luxo');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Lamborghini Reventon','Descrição Lamborghini Reventon','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Lamborghini_Reventon.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/lamborghini _reventon.mp4','-23.564224','-46.653156','luxo');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Leblanc Mirabeau','Descrição Leblanc Mirabeau','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Leblanc_Mirabeau.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/leblanc_mirabeau.mp4','-23.564224','-46.653156','luxo');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Shelby Supercars Ultimate','Descrição Shelby Supercars Ultimate','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Shelby_Supercars_Ultimate.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/shelby.mp4','-23.564224','-46.653156','luxo');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Pagani Zonda','Descrição Pagani Zonda','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Pagani_Zonda.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/pagani_zonda.mp4','-23.564224','-46.653156','luxo');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Koenigsegg CCX','Descrição Koenigsegg CCX','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Koenigsegg_CCX.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/koenigsegg.mp4','-23.564224','-46.653156','luxo');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Mercedes SLR McLaren','Descrição Mercedes SLR McLaren','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Mercedes_McLaren.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/mclaren_slr.mp4','-23.564224','-46.653156','luxo');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Rolls Royce Phantom','Descrição Rolls Royce Phantom','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Rolls_Royce_Phantom.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/rolls_royce.mp4','-23.564224','-46.653156','luxo');
insert into cursos_crud.carros (nome,descricao,url_foto,url_video,latitude,longitude,tipo) VALUES('Lexus LFA','Descrição Lexus LFA','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/Lexus_LFA.png','http://www.livroandroid.com.br/livro/cursos_crud.carross/luxo/lexus.mp4','-23.564224','-46.653156','luxo');
